cds:
  odata-v4.endpoint.path: "/api"
  security.mock.users:
    - name: admin
      password: admin
    - name: user
      password: user
server.servlet.encoding:
  charset: UTF-8
  force: true

---
spring:
  config.activate.on-profile: default
cds:
  data-source:
    auto-config.enabled: false